version: "1"
services:
  cloud-care:
    image: cloud-care:latest
    build:
      tags:
        - "cloud-care:latest"
      context: ./
      dockerfile: Dockerfile
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - "80:80"
