const permissions = {
    "DASHBOARD_READ": "DASHBOARD_READ",
    "APPOINTMENTS_READ": "APPOINTMENTS_READ",
    "APPOINTMENTS_WRITE": "APPOINTMENTS_WRITE",
    "APPOINTMENTS_EDIT": "APPOINTMENTS_EDIT",
    "APPOINTMENTS_DELETE": "APPOINTMENTS_DELETE",
    "SCHEDULES_READ": "SCHEDULES_READ",
    "SCHEDULES_WRITE": "SCHEDULES_WRITE",
    "SCHEDULES_EDIT": "SCHEDULES_EDIT",
    "SCHEDULES_DELETE": "SCHEDULES_DELETE",
    "PATIENTS_READ": "PATIENTS_READ",
    "PATIENTS_WRITE": "PATIENTS_WRITE",
    "PATIENTS_EDIT": "PATIENTS_EDIT",
    "PATIENTS_DELETE": "PATIENTS_DELETE",
    "USERS_READ": "USERS_READ",
    "USERS_WRITE": "USERS_WRITE",
    "USERS_EDIT": "USERS_EDIT",
    "USERS_DELETE": "USERS_DELETE",
    "STAFF_READ": "STAFF_READ",
    "STAFF_WRITE": "STAFF_WRITE",
    "STAFF_EDIT": "STAFF_EDIT",
    "STAFF_DELETE": "STAFF_DELETE",
    "LOGS_READ": "LOGS_READ"
} as const;


export default permissions;