import dayjs from "dayjs";
import type { TStaffGet } from "@/server/api/ApiTypeFactory";

type staffType = TStaffGet["data"][0];


export const Tempdata: staffType[] = [
    {
        id: "cls3il28i0008fbmg7kln4oay",
        title: "Ms",
        firstName: "Alice",
        lastName: "Smith",
        dateOfBirth: dayjs("1990-01-01").toDate(),
        gender: "female",
        image: "/img/avatar/person-female.png",
        email: "alice.smith@example.com",
        phone: "+9876543210",
        NIC: "6543210987",
        Passport: null,
        idNumber: "s23523293433",
        admin: null,
        nurse: {
            id: "cls3il28i0009fbmgldafghlv",
            staffId: "cls3il28i0008fbmg7kln4oay",
            OptRoomsid: null,
        },
        doctor: null,
    },
    {
        id: "clqlak74m0003e0nbpwybhero",
        title: "Ms",
        firstName: "Fathima",
        lastName: "humaina",
        dateOfBirth: dayjs("1990-01-01").toDate(),
        gender: "male",
        image: "/img/avatar/person-male.png",
        email: "humaina@gmail.com",
        phone: "+941234531565",
        NIC: "1234597896",
        Passport: null,
        idNumber: "s23523293433",
        admin: {
            id: "clqlak74m0004e0nbru2qbfk0",
            department: "Administration",
            staffId: "clqlak74m0003e0nbpwybhero",
        },
        nurse: null,
        doctor: null,
    },
    {
        id: "clrbwog260000qvxijkzfr5mp",
        title: "Mr",
        firstName: "John",
        lastName: "kile",
        dateOfBirth: dayjs("1990-04-01").toDate(),
        gender: "male",
        image: "/img/avatar/person-male.png",
        email: "John@gmail.com",
        phone: "+94123456565",
        NIC: "1234527596",
        Passport: null,
        idNumber: "s23523293433",
        admin: {
            id: "clrbwog260001qvxiwex9t6q8",
            department: "Administration",
            staffId: "clrbwog260000qvxijkzfr5mp",
        },
        nurse: null,
        doctor: null,
    },
    {
        id: "cls3ikk9r0006fbmgpavggmb1",
        title: "Mr",
        firstName: "John",
        lastName: "Doe",
        dateOfBirth: dayjs("1990-01-15").toDate(),
        gender: "male",
        image: "/img/avatar/person-male.png",
        email: "john.doe@example.com",
        phone: "+1234567890",
        NIC: "7890123456",
        Passport: null,
        idNumber: "s23523293433",
        admin: null,
        nurse: null,
        doctor: {
            id: "cls3ikk9r0007fbmgy9i70xgw",
            specialization: "CARDIOLOGIST",
            staffId: "cls3ikk9r0006fbmgpavggmb1",
        },
    },
    {
        id: "cls3imor2000cfbmg4xcrxwcw",
        title: "Mrs",
        firstName: "Lisa",
        lastName: "Davis",
        dateOfBirth: dayjs("1998-01-01").toDate(),
        gender: "female",
        image: "/img/avatar/person-female.png",
        email: "lisa.davis@example.com",
        phone: "+9988776655",
        NIC: "5678901234",
        Passport: null,
        idNumber: "s23523293433",
        admin: null,
        nurse: {
            id: "cls3imor2000dfbmg4xjnwqbm",
            staffId: "cls3imor2000cfbmg4xcrxwcw",
            OptRoomsid: null,
        },
        doctor: null,
    },
    {
        id: "clrbyyll70002xhii018n36us",
        title: "Mr",
        firstName: "mohamed",
        lastName: "farnas",
        dateOfBirth: dayjs("1999-01-01").toDate(),
        gender: "male",
        image: "/img/avatar/person-male.png",
        email: "mohammedfarnas@gmail.com",
        phone: "+94163456565",
        NIC: "1234597596",
        Passport: null,
        idNumber: "s23523293433",
        admin: {
            id: "clrbyyll70003xhii940frvxw",
            department: "Administration",
            staffId: "clrbyyll70002xhii018n36us",
        },
        nurse: null,
        doctor: null,
    },
    {
        id: "cls3ienfo0004fbmg5aqzc2yh",
        title: "Mr",
        firstName: "mohamed",
        lastName: "farnas",
        dateOfBirth: dayjs("1999-06-01").toDate(),
        gender: "male",
        image: "/img/avatar/person-male.png",
        email: "farmas123@gmail.com",
        phone: "+94183456565",
        NIC: "1234497596",
        Passport: null,
        idNumber: "s23523293433",
        admin: null,
        nurse: null,
        doctor: {
            id: "cls3ienfo0005fbmgg4yhv1nf",
            specialization: "GENERAL_PRACTITIONER",
            staffId: "cls3ienfo0004fbmg5aqzc2yh",
        },
    },
];