name: Receive PR

# read-only repo token
# no access to secrets
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: install dependacies
        run: npm install
      - name: Build
        run: npm run build
      - name: zip artifact
        run: zip -r cloudCare-app.zip . # path to the build folder
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: cloudCare-app
          path: cloudCare-app.zip # path to the build folder
